### ISSUE TITLE
dygonzo contributor access

### ISSUE THREAD

**Issue by dygonzo** [dgonzo27/py-iot-utils#19]
**Why would you like to contribute to this project?**
As a lead developer on an enterprise IoT Platform, I would love to contribute to this project as I leverage and use all of these packages in our platform.  Allowing me to contribute would offer valuable insight into industry adoption while simultaneously allowing me to support stateless interactions that can be leveraged outside of our platform.

**What are your qualifications?**
You know me - I wrote this thang.

**What are you looking to contribute and how many hours per week?**
Probably 6 - 10 hours per week, looking to contribute new features, maintenance and documentation.

**Do you understand that these contributions are open-source and there is no pay for contributing?**
Yes.

**Comment by dgonzo27** [comment]
Done, welcome aboard!
